### ISSUE TITLE
Tensorflow Variables: Initializer and dtype do not match

### ISSUE THREAD

**Issue by braun-steven** [SPFlow/SPFlow#15]
The generation of a Tensorflow variable from a gaussian node goes wrong if the initializer dtype does not match the dtype that has been passed as option [here](https://github.com/SPFlow/SPFlow/blob/f69dcdff395daaac146e241531d14648e84e536c/src/spn/structure/leaves/parametric/Tensorflow.py#L17) (and probably also in all other usages of `tf.variable(...)`).

Exemplary code
```python
from spn.structure.leaves.parametric.Parametric import Gaussian
from spn.structure.leaves.parametric.Tensorflow import gaussian_to_tf_graph
import numpy as np

var = gaussian_to_tf_graph(
    node=Gaussian(mean=0.0, stdev=1.0), dtype=np.float64
)
```
Results in:
```
Traceback (most recent call last):
  File "SPFlow/main.py", line 192, in <module>
    test_tf_opt()
  File "SPFlow/main.py", line 165, in test_tf_opt
    node=Gaussian(mean=float(0.0), stdev=float(1.0)), dtype=np.float64
  File "SPFlow/src/spn/structure/leaves/parametric/Tensorflow.py", line 17, in gaussian_to_tf_graph
    mean = tf.get_variable("mean", initializer=node.mean, dtype=dtype)
  File "SPFlow/env/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "SPFlow/env/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1214, in get_variable
    "don't match." % (init_dtype, dtype))
ValueError: Initializer type '<dtype: 'float32'>' and explicit dtype '<class 'numpy.float64'>' don't match.
```

A case where this happens is when you first learn an SPN from data and want to optimize the weights in Tensorflow afterwards:

```python
from spn.algorithms.LearningWrappers import learn_classifier, learn_parametric
from spn.structure.leaves.parametric.Parametric import Categorical, Gaussian
from spn.structure.Base import Context
from spn.gpu.TensorFlow import optimize_tf
from spn.algorithms.Inference import log_likelihood
import numpy as np

# Sample data
train_data = np.array([1.0, 0.0, 1.0], dtype=np.float64).reshape(-1, 3)

# Learn SPN
spn = learn_classifier(
    train_data,
    ds_context=Context(
        parametric_types=[Gaussian, Gaussian, Categorical]
    ).add_domains(train_data),
    spn_learn_wrapper=learn_parametric,
    label_idx=2,
    cpus=-1,
)

# Run weight optimization 
optimized_spn = optimize_tf(spn, train_data) # <-- tf variable generation fails here
lloptimized = log_likelihood(optimized_spn, train_data)
print(lloptimized, np.exp(lloptimized))
```

A possible fix would be to replace:
```python
tf.get_variable(
    "mean", 
    initializer=node.mean, 
    dtype=dtype
)
```

with
```python
dtype = np.dtype(dtype).type
tf.get_variable(
    "mean", 
    initializer=dtype(node.mean), 
    dtype=dtype
)
```

**Comment by pranavsubramani** [comment]
@steven-lang I was wondering if this was already fixed, or if not, do you want to create a PR and I'll review it and accept 👍

**Comment by alejandromolinaml** [comment]
It’s more complicated than that.


We had talked about it, basically the problem is that tensorflow doesn’t
allow for probability objects of type float64.
At least it didn’t back then.

We should revise this in light of tensorflow.com/probabilities
