### ISSUE TITLE
learn_mspn_with_missing throws error with no leaves parameter specified

### ISSUE THREAD

**Issue by cvoelcker** [SPFlow/SPFlow#30]
### Description

While trying to train an mspn from data with missing values, the error occurred in the first call to the local subfunction l_mspn... Even when specifying the parameter leaves for the outer function, scoping does not seem to wor for the inner function.

#### Encountered behavior:

The scoping of leaves seems to be wrong:
```
.../site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    ds_context)
  File ".../site-packages/spn/algorithms/LearningWrappers.py", line 109, in learn_mspn_with_missing
    return l_mspn_missing(data, ds_context, cols, rows, min_instances_slice, threshold, linear, ohe)
  File ".../site-packages/spn/algorithms/LearningWrappers.py", line 99, in l_mspn_missing
    if leaves is None:
UnboundLocalError: local variable 'leaves' referenced before assignment
```

### Additional Information

- Operating System: linux arch
- Python Version: 3.7

**Comment by alejandromolinaml** [comment]
fixed in commit  367f58d
