### ISSUE TITLE
importing learn_parametric crash on Windows

### ISSUE THREAD

**Issue by dedo24397** [SPFlow/SPFlow#42]
###Description 

Just by importing learn_parametric makes the whole script crash on Windows. To be sure it was that function to cause the error, I created a script whit just the import statement and the result was the same.

###Environement

- Operating System: Windows 10
- Python Version: 3.7.2 / 3.6.8

###Stacktrace

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 114, in _main
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
    prepare(preparation_data)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 225, in prepare
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 263, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\main.py", line 2, in <module>
    from StackSPN import StackSPN
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\StackSPN.py", line 1, in <module>
    from spn.algorithms.LearningWrappers import learn_parametric
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\LearningWrappers.py", line 9, in <module>
    run_name="__mp_main__")
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\main.py", line 2, in <module>
    from StackSPN import StackSPN
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\StackSPN.py", line 1, in <module>
    from spn.algorithms.LearningWrappers import learn_parametric
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\LearningWrappers.py", line 9, in <module>
    from spn.algorithms.StructureLearning import get_next_operation, learn_structure
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\StructureLearning.py", line 33, in <module>
    pool = multiprocessing.Pool(processes=cpus)
    exitcode = _main(fd)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 119, in Pool
    from spn.algorithms.StructureLearning import get_next_operation, learn_structure
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\StructureLearning.py", line 33, in <module>
    pool = multiprocessing.Pool(processes=cpus)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 119, in Pool
    run_name="__mp_main__")
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    context=self.get_context())
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 176, in __init__
    exec(code, run_globals)
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\main.py", line 2, in <module>
Traceback (most recent call last):
    context=self.get_context())
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 176, in __init__
  File "<string>", line 1, in <module>
    from StackSPN import StackSPN
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\StackSPN.py", line 1, in <module>
    from spn.algorithms.LearningWrappers import learn_parametric
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\LearningWrappers.py", line 9, in <module>
    from spn.algorithms.StructureLearning import get_next_operation, learn_structure
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\StructureLearning.py", line 33, in <module>
    pool = multiprocessing.Pool(processes=cpus)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\process.py", line 112, in start
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    self._repopulate_pool()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\process.py", line 112, in start
    exitcode = _main(fd)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    self._repopulate_pool()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\process.py", line 112, in start
    run_name="__mp_main__")
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 263, in run_path
    self._popen = self._Popen(self)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    self._popen = self._Popen(self)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    self._popen = self._Popen(self)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    pkg_name=pkg_name, script_name=fname)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    return Popen(process_obj)
    exec(code, run_globals)
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\main.py", line 2, in <module>
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    return Popen(process_obj)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    from StackSPN import StackSPN
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\StackSPN.py", line 1, in <module>
    return Popen(process_obj)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    from spn.algorithms.LearningWrappers import learn_parametric
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\LearningWrappers.py", line 9, in <module>
    from spn.algorithms.StructureLearning import get_next_operation, learn_structure
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\StructureLearning.py", line 33, in <module>
    pool = multiprocessing.Pool(processes=cpus)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 119, in Pool
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    context=self.get_context())
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 176, in __init__
    _check_not_importing_main()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    _check_not_importing_main()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    _check_not_importing_main()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    self._repopulate_pool()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    w.start()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    _check_not_importing_main()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\main.py", line 2, in <module>
    from StackSPN import StackSPN
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\StackSPN.py", line 1, in <module>
    from spn.algorithms.LearningWrappers import learn_parametric
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\LearningWrappers.py", line 9, in <module>
    from spn.algorithms.StructureLearning import get_next_operation, learn_structure
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\StructureLearning.py", line 33, in <module>
    pool = multiprocessing.Pool(processes=cpus)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_data
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\main.py", line 2, in <module>
    from StackSPN import StackSPN
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\StackSPN.py", line 1, in <module>
    from spn.algorithms.LearningWrappers import learn_parametric
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\LearningWrappers.py", line 9, in <module>
    from spn.algorithms.StructureLearning import get_next_operation, learn_structure
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\StructureLearning.py", line 33, in <module>
    pool = multiprocessing.Pool(processes=cpus)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    _check_not_importing_main()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    train = np.array(np.genfromtxt('train.csv', delimiter=',')[:, :3],
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\numpy\lib\npyio.py", line 1761, in genfromtxt
    first_line = _decode_line(next(fhd), encoding)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\main.py", line 2, in <module>
    from StackSPN import StackSPN
  File "C:\Users\dedo2\OneDrive - Università degli Studi di Bari\Tesi\SPN\1_Layer_Bernoulli\StackSPN.py", line 1, in <module>
    from spn.algorithms.LearningWrappers import learn_parametric
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\LearningWrappers.py", line 9, in <module>
    from spn.algorithms.StructureLearning import get_next_operation, learn_structure
  File "C:\Users\dedo2\ONEDRI~1\Tesi\venv\lib\site-packages\spn\algorithms\StructureLearning.py", line 33, in <module>
    pool = multiprocessing.Pool(processes=cpus)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "c:\users\dedo2\appdata\local\programs\python\python37\Lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by dedo24397** [comment]
Update: works well with jupyter notebook in the same environement

**Comment by alejandromolinaml** [comment]
unfortunately I don't have a windows machine. Could you compare the difference between the windows/jupyter environments?

**Comment by dedo24397** [comment]
I noticed that the exception is not thrown if you run the instruction via the python interpreter.
> 
> 
> Could you compare the difference between the windows/jupyter environments?

The environments were the same (I ran the notebook server on the same machine).

**Comment by alejandromolinaml** [comment]
what do you mean by running via the python interpreter?

so, I'm glad that it works in some cases, that tells us there is a way for it to work. 
maybe you can help me debug this? 

should we skype? do you have my email?

I can't reproduce the bug as I don't have a windows machine.

**Comment by dedo24397** [comment]
> 
> 
> what do you mean by running via the python interpreter?

starting a python interpreter in a terminal and executing the import instruction works

> should we skype? do you have my email?
> 
> I can't reproduce the bug as I don't have a windows machine.

at the moment i can't use skype but i'm glad to help since i'm using this library

**Comment by pranavsubramani** [comment]
Hello @dedo24397, 

I tested the above on a windows 10 machine and have attached a screenshot below, it appears to work fine, the python version being used is 3.6.8

![image](https://user-images.githubusercontent.com/10266704/54627922-c4205780-4a4a-11e9-90e8-c2bfeb04789c.png)


Have you tried a fresh install, (so purging the entire repository + reinstalling).

Also what version of spflow are you using?

**Comment by dedo24397** [comment]
> 
> 
> Hello @dedo24397,
> 
> I tested the above on a windows 10 machine and have attached a screenshot below, it appears to work fine, the python version being used is 3.6.8
> 
> ![image](https://user-images.githubusercontent.com/10266704/54627922-c4205780-4a4a-11e9-90e8-c2bfeb04789c.png)

as I told, it works using the python interpreter as you did. It doesn't work if you put that instruction inside a script and the run it

**Comment by alejandromolinaml** [comment]
could you post a minimal reproducible example script? 
and show us how you call it?

**Comment by dedo24397** [comment]
`from spn.algorithms.LearningWrappers import learn_parametric`

even a script with this single import crashes. As mentioned by @pranavsubramani , this crash doesn't happen if you use the python console (with IDLE or in a terminal)

**Comment by pranavsubramani** [comment]
For @alejandromolinaml  here is a stack trace of the output:

`File "<string>", line 1, in <module>
  File "C:\Users\prana\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\prana\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\prana\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\prana\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)`

The "windows" way to generate multiple threads in python is using `spawn` process, so the parent python process will start a new python interpreter process. For some reason, there is no "error" in the stack trace, but I'll run through a detailed stack trace and let you know of what I find

**Comment by pranavsubramani** [comment]
What's happening here is actually an issue with how you're using the `learn_parametric` function. Since there is no

`if __name__ == "__main__":
    # run some code here
`

The reason why this is necessary is because whenever there is no entrypoint to the program (through the main), every subprocess will execute a new thread from the first line of the program (to be precise, the subprocess looks for the main module, and when it cannot find it, it will execute the program from the first line). This thread will attempt to get a hold of the cpu as well, so your code intends to create new python interpreters in each subprocess that you've created. But sometimes a process is created while the other is still in the bootstrapping phase. This creates inconsistent behavior and produces the stack trace which you linked above. This does not happen in Ubuntu/Mac OSX as an additional note. 

Regarding the fix -- I am not entirely sure how to fix this yet, but we need to ensure that there is a guard against recursively creating subprocesses, if you do have a main module in your scripts, this is not going to happen.

**Comment by dedo24397** [comment]
actually i tried to put my code into a main file as you said, but same result

**Comment by pranavsubramani** [comment]
That's very strange, can I see the file that you are trying to run? when I just put it within my main function I obtain no issues at all.

**Comment by dedo24397** [comment]
i'm importing the library in a class and then using it in another file with a main function. I also added

`if __name__ == "__main__":
     main()`

as you suggested

**Comment by pranavsubramani** [comment]
Alright, it appears to work if you throw the import within a module, but appears to not work if it is kept at the top level of the file. I think this may have to do with setting the pool variable as a global variable, this appears to not be an issue on Linux but appears to cause issues on windows.

**Comment by MoritzKulessa** [comment]
Yes, it is a Windows problem and, in particluar, the pool variable is the problem as described above. A possible fix could be to check the OS during runtime and then decide whether to allow parallelization or not.

For my workaround, I have removed the parallelization:
(1) "spn.algorithms.StructureLearning" lines 24-33 comment:

<pre><code>
...
#import multiprocessing
#import os

#parallel = True

#if parallel:
#    cpus = max(1, os.cpu_count() - 2)  # - int(os.getloadavg()[2])
#else:
#    cpus = 1
#pool = multiprocessing.Pool(processes=cpus)
...
</code></pre>


(2) "spn.algorithms.StructureLearning" lines 276-281 comment/uncomment:

<pre><code>
...
#result_nodes = pool.starmap(create_leaf, local_children_params)
result_nodes = []
for l in local_children_params:
      result_nodes.append(create_leaf(*l))
result_nodes = [create_leaf(*l) for l in local_children_params]
...
</code></pre>

**Make sure u have removed "tqdm"**


(3) "spn.algorithms.CnetStructureLearning" lines 25-29 comment:

<pre><code>
...
#import multiprocessing
#import os

#cpus = max(1, os.cpu_count() - 2)  # - int(os.getloadavg()[2])
#pool = multiprocessing.Pool(processes=cpus)
...
</code></pre>
(pool is defined but not used in this module)

**Comment by felixdivo** [comment]
I fixed it by dropping into the [*Windows-Subsystem for Linux* (WSL)](https://docs.microsoft.com/de-de/windows/wsl/). Everything worked fine in there.

**Comment by felixdivo** [comment]
I had to revert to Windows due to some other problems. I found a simpler fix that one could add to get rid of the error:

```python
if parallel:
    import multiprocessing
    cpus = max(1, os.cpu_count() - 2)  # - int(os.getloadavg()[2])
else:
    import multiprocessing.dummy as multiprocessing
    cpus = 1

pool = multiprocessing.Pool(processes=cpus)
```

There is no need to edit `spn.algorithms.StructureLearning` lines 276-281 after applying this change to the start of `spn.algorithms.StructureLearning` and `spn.algorithms.CnetStructureLearning`.

**Comment by felixdivo** [comment]
Moving the line `pool = multiprocessing.Pool(processes=cpus)` into `def learn_structure(...)` in `spn.algorithms.StructureLearning` also re-anables parallelism. It works fine in my case and there is no need to exclude Windows platforms from parallelism in that case.
