### ISSUE TITLE
EM on non-tree structures returns a broadcast error

### ISSUE THREAD

**Issue by RenatoGeh** [SPFlow/SPFlow#71]
### Description

Running `EM_optimization` on a non-tree structure returns a broadcast error. Below is a minimal example for reproducibility:

```python
import spn
from spn.structure.leaves.parametric.Parametric import Gaussian, Bernoulli
import spn.structure.Base as Base
import spn.algorithms.Sampling as Sampling
import numpy as np

SEED = 101

def rand_weights(m = 2, n = 5):
  r = np.random.rand(n, m)
  return (r/r.sum(axis=1)[:,np.newaxis]).tolist()

def gen_spn(true_spn = False):
  if true_spn:
    W = [[0.3, 0.7], [0.6, 0.4], [0.5, 0.5], [0.2, 0.8], [0.45, 0.55]]
    W.reverse()
  else:
    W = rand_weights()

  X_11 = Bernoulli(p=0.2, scope=[0])
  X_12 = Bernoulli(p=0.4, scope=[0])
  X_21 = Bernoulli(p=0.6, scope=[1])
  X_22 = Bernoulli(p=0.8, scope=[1])

  S_0 = Base.Sum(weights=W.pop(), children=[X_11, X_12])
  S_1 = Base.Sum(weights=W.pop(), children=[X_21, X_22])
  S_2 = Base.Sum(weights=W.pop(), children=[X_11, X_12])
  S_3 = Base.Sum(weights=W.pop(), children=[X_21, X_22])

  P_0 = Base.Product(children=[S_0, S_1])
  P_1 = Base.Product(children=[S_2, S_3])

  R = Base.Sum(weights=W.pop(), children=[P_0, P_1])

  Base.assign_ids(R)
  Base.rebuild_scopes_bottom_up(R)

  M = {'X_11': X_11, 'X_12': X_12, 'X_21': X_21, 'X_22': X_22,
       'S_0': S_0, 'S_1': S_1, 'S_2': S_2, 'S_3': S_3,
       'P_0': P_0, 'P_1': P_1,
       'R': R}

  return R, M

def generate_data(S, n=1000):
  return Sampling.sample_instances(S, np.array([np.nan, np.nan] * n).reshape(-1, len(S.scope)),
                                   np.random.mtrand.RandomState(SEED))

TRUE_SPN, TRUE_SPN_MAP = gen_spn(true_spn = True)
D = generate_data(TRUE_SPN)
SPN, SPN_MAP = gen_spn()

def print_spn(S_MAP):
  for k in S_MAP:
    print(k, S_MAP[k].parameters)

def main():
  spn.algorithms.EM.EM_optimization(SPN, D, iterations=10)
  print('True values:')
  print_spn(TRUE_SPN_MAP)
  print('====')
  print_spn(SPN_MAP)

if __name__ == '__main__':
  main()
```

Through some debugging with `pdb`, I found that whenever a node has two or more parents, the `parent_results` array has length greater than one, causing `merge_gradients` to return an array of size double the expected length. This is what apparently causes the error.

#### Expected behavior:

Return an SPN with EM optimized weights.

#### Encountered behavior:

Numpy broadcast error:

```
Traceback (most recent call last):
  File "minimal.py", line 65, in <module>
    main()
  File "minimal.py", line 58, in main
    spn.algorithms.EM.EM_optimization(SPN, D, iterations=10)
  File "/usr/lib/python3.8/site-packages/spn/algorithms/EM.py", line 61, in EM_optimization
    gradients = gradient_backward(spn, lls_per_node)
  File "/usr/lib/python3.8/site-packages/spn/algorithms/Gradient.py", line 81, in gradient_backward
    eval_spn_top_down(
  File "/usr/lib/python3.8/site-packages/spn/structure/Base.py", line 445, in eval_spn_top_down
    result = func(n, param, **args)
  File "/usr/lib/python3.8/site-packages/spn/algorithms/Gradient.py", line 18, in leaf_gradient_backward
    gradient_result[:, node.id] = gradients
ValueError: could not broadcast input array from shape (2000) into shape (1000)
```

### Additional Information

- Operating System: Arch Linux 5.5.4 x86_64
- Python Version: 3.8.1

**Comment by braun-steven** [comment]
Since we're currently working on a rewrite from scratch and none of the old code will be reused, this bug won't be present in the v1.0.0 release.
