### ISSUE TITLE
Error in plot_spn

### ISSUE THREAD

**Issue by JayMan91** [SPFlow/SPFlow#78]
### Description
When I tried to print the network with the function plot_spn using the following piece of code,
```python
# Your code here
from spn.structure.leaves.parametric.Parametric import Categorical
from spn.io.Graphics import plot_spn

spn = 0.4 * (Categorical(p=[0.2, 0.8], scope=0) *
             (0.3 * (Categorical(p=[0.3, 0.7], scope=1) *
                     Categorical(p=[0.4, 0.6], scope=2))
            + 0.7 * (Categorical(p=[0.5, 0.5], scope=1) *
                     Categorical(p=[0.6, 0.4], scope=2)))) \
    + 0.6 * (Categorical(p=[0.2, 0.8], scope=0) *
             Categorical(p=[0.3, 0.7], scope=1) *
             Categorical(p=[0.4, 0.6], scope=2))
plot_spn(spn, 'test.png')
```
I got the following error
```python-traceback
Traceback (most recent call last):
  File "/spflow/lib/python3.7/site-packages/pydot.py", line 1915, in create
    working_dir=tmp_dir,
  File "/spflow/lib/python3.7/site-packages/pydot.py", line 136, in call_graphviz
    **kwargs
  File "/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spn_codes.py", line 37, in <module>
    plot_spn(spn)
  File "/spflow/lib/python3.7/site-packages/spn/io/Graphics.py", line 60, in plot_spn
    pos = graphviz_layout(g, prog="dot")
  File "/spflow/lib/python3.7/site-packages/networkx/drawing/nx_pydot.py", line 268, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
  File "/spflow/lib/python3.7/site-packages/networkx/drawing/nx_pydot.py", line 316, in pydot_layout
    D_bytes = P.create_dot(prog=prog)
  File "/spflow/lib/python3.7/site-packages/pydot.py", line 1723, in new_method
    format=f, prog=prog, encoding=encoding)
  File "/spflow/lib/python3.7/site-packages/pydot.py", line 1922, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.

```

### Additional Information

- Operating System: Ubuntu 18.04.4 
- Python Version: Python 3.7.3

Thanks for your consideration.

**Comment by alejandromolinaml** [comment]
try installing graphviz

sudo apt-get install graphviz

**Comment by JayMan91** [comment]
Thank you very much!!!
