### ISSUE TITLE
Getting error in plot_spn running introductory example

### ISSUE THREAD

**Issue by jenieto** [SPFlow/SPFlow#91]
### Description
An error is thrown when trying to run the introductory example specified in https://github.com/SPFlow/SPFlow using spflow 0.0.40

#### Expected behavior:
The spn is plotted when executing plot_spn(spn, 'basicspn.png')

#### Encountered behavior:
The following error is found:

Traceback (most recent call last):
  File "/home/jesus/src/spflow-samples/samples.py", line 13, in <module>
    plot_spn(spn, 'basicspn.png')
  File "...../python3.7/site-packages/spn/io/Graphics.py", line 80, in plot_spn
    g, pos=pos, edge_labels=nx.get_edge_attributes(g, "weight"), font_size=16, clip_on=False, alpha=0.6
TypeError: draw_networkx_edge_labels() got an unexpected keyword argument 'clip_on'

### Additional Information

- Operating System: Ubuntu 20.04.1 LTS
- Python Version: 3.7.5

**Comment by hayesall** [comment]
Duplicate of #78, and fixed in #90 

Upgrading should resolve this.

**Comment by jenieto** [comment]
Sorry, upgrading to what version? I am currently using version 0.0.40, which is the latest one according to this https://pypi.org/project/spflow/

**Comment by hayesall** [comment]
My mistake, the patch might not have been released on PyPi yet.

It should be on the master branch:

```bash
git clone git@github.com:SPFlow/SPFlow.git
cd SPFlow/src/
pip install -e .
```

**Comment by jenieto** [comment]
All right, thank you for that. Do you know if there is any plan to release it to PyPi?

**Comment by alejandromolinaml** [comment]
I’m working on that :)

**Comment by alejandromolinaml** [comment]
could you check version 0.0.41?

**Comment by jenieto** [comment]
it works great now, thank you!

**Comment by felixdivo** [comment]
Already done :)
